version: "3"
services:
    postgres:
      image: mdillon/postgis:9.6
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=zoom
        - POSTGRES_PASSWORD=zoom
        - POSTGRES_DB=zoom
    server:
      image: zoom-csv-mapper_app
      command: bash -c "sh ZOOM/scripts setup_project.sh &&
        python ZOOM/manage.py runserver 127.0.0.1:8000"
      #command: ["python", "ZOOM/manage.py", "runserver", "0.0.0.0:8000"]
      environment:
      - ZOOM_DB=postgres
      depends_on:
      - postgres
      ports:
      - "8000:8000"
      tty: true